name: url-shortener-project
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: urlshortener_webapp_RabbitMQ
    ports:
      - "${RABBITMQ_MANAGEMENT_HOST_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:7-alpine
    container_name: urlshortener_webapp_Redis

  db:
    image: postgres:16
    container_name: urlshortener_webapp_DB
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: urlshortener_webapp_API
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    environment:
      ConnectionStrings__Postgres: "Host=db;Port=${POSTGRES_CONTAINER_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};GSS Encryption Mode=Disable"
      ConnectionStrings__Redis: "${REDIS_CONNECTION_STRING}"
      ConnectionStrings__RabbitMq: "${RABBITMQ_CONNECTION_STRING}"
    
    depends_on:
      - redis
      - db
      - rabbitmq

volumes:
  pgdata:
